### ISSUE TITLE
path[/^[^:]+/] is not working correctly with windows path

### ISSUE THREAD

**Issue by iamdionysus** [minitest/minitest-debugger#3]
In `lib\minitest\debugger.rb`, line 15 to 18 has

``` ruby
if path then
  path = path[/^[^:]+/]
  SCRIPT_LINES__[path] = File.readlines(path)
end
```

If I use windows, the path is something like `C:/Ruby22-x64/lib/.../kernel_require.rb:128:in 'require'`. This pattern match will only get `C` out of path and `File.readlines(path)` throws exception.

**Comment by iamdionysus** [comment]
`^([a-zA-Z]:)?[^:]+` pattern seems to be working both for windows and linux but I'm not sure.

**Comment by zenspider** [comment]
Pull request?

**Comment by zenspider** [comment]
No response in 6 years. closing.
